import Container from "@/layouts/Container";
import HeaderLayout from "@/layouts/HeaderLayout";
import MacroLayout from "@/layouts/MacroLayout";
import SectionLayout from "@/layouts/SectionLayout";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import Header from "../_components/Header";
import "../globals.css";
import SignOnNav from "./_components/SignOnNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container>
          <SignOnNav />
          <HeaderLayout>
            <Header />
          </HeaderLayout>
          <MacroLayout>
            <main>
              <SectionLayout>{children}</SectionLayout>
            </main>
          </MacroLayout>
        </Container>
      </body>
    </html>
  );
}
